import Head from 'next/head';

type CustomHeadProps = {
  title: string,
  description?: string
}

const CustomHead = ({title, description}: CustomHeadProps) => {
  const defaultTitle = 'Mykola Tokarskyi | Test';
  const defaultDescription = 'Generated by create next app';

  return (
    <Head>
      <title>{title ? `${title} | ${defaultTitle}` : defaultTitle}</title>
      <meta name="description" content={description || defaultDescription} />
    </Head>
  );
};

export default CustomHead;